LojaDeGames/Controllers/ClienteController.cs
using LojaDeGames.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace LojaDeGames.Controllers
{
   
    public class ClienteController : Controller
    {
        // GET: Cliente
        private ApplicationDbContext _context;

        public ClienteController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        //static List<Cliente> listaCliente = new List<Cliente>()
        //{
        //    new Cliente {Id = 1, Nome = "Leonardo Reis",Cpf = 15645648, Endereco = "Jaraguá do Sul" },
        //    new Cliente {Id = 2, Nome = "Lauro Reis",Cpf = 15645648, Endereco = "Arroio do Sal" },
        //    new Cliente {Id = 3, Nome = "Anderson Boer",Cpf = 15645648, Endereco = "Torres" },
        //    new Cliente {Id = 4, Nome = "Neuza Maria",Cpf = 15645648, Endereco = "Torres" },
        //    new Cliente {Id = 5, Nome = "Luis Alberto Boer",Cpf = 15645648, Endereco = "Torres" },
        //};
        public ActionResult IndexCliente()
        {

            var clienteIndexView = new ClienteIndexViewModel()
            {
                Clientes = _context.Clientes.ToList()
            };


            return View(clienteIndexView);
            
        }



        public ActionResult DetalhesClientes(int id)
        {
            
            if (id > _context.Clientes.Count()) return HttpNotFound();

            Cliente clientesDetalhe = _context.Clientes.Find(id);//(clientes => clientes.Id == id);

            return View(clientesDetalhe);

        }
        [Authorize(Roles = "CanManageCustomers")]

        public ActionResult New()
        {
            var viewModel = new ClienteIndexViewModel();
            
            return View("FormCliente", viewModel);
        }


        [HttpPost] // só será acessada com POST
        [ValidateAntiForgeryToken]
        public ActionResult Save([Bind(Include = "Id,Nome,Cpf,Endereco")]Cliente cliente) // recebemos um cliente
        {
            ModelState.Remove("cliente.Id");

            if (!ModelState.IsValid)
            {
                var viewModel = new ClienteIndexViewModel
                {
                    Cliente = cliente
                };

                return View("FormCliente", viewModel);
            }

            if (cliente.Id != 0)
            {
                _context.Entry(cliente).State = System.Data.Entity.EntityState.Modified;
            }
            else {
                _context.Clientes.Add(cliente);
            }
            // armazena o cliente em memória
            
            // faz a persistência
            _context.SaveChanges();
            // Voltamos para a lista de clientes
            return RedirectToAction("IndexCliente");
        }

        public ActionResult Edit(int id)
        {
            var cliente = _context.Clientes.SingleOrDefault(c => c.Id == id);

            if (cliente == null)
                return HttpNotFound();

            var viewModel = new ClienteIndexViewModel
            {
                Cliente = cliente
            };

            return View("FormCliente", viewModel);
        }

    //    [Authorize(Roles = "CanManageCustomers")]

        public ActionResult Delete(int id)
        {

            Cliente cliente = _context.Clientes.SingleOrDefault(c => c.Id == id);

            if (cliente == null)
            {
                return HttpNotFound();
            }
            else
            {
                _context.Clientes.Remove(cliente);
                _context.SaveChanges();
                return RedirectToAction("IndexCliente",cliente);
              
            }
        }

        //[AcceptVerbs(HttpVerbs.Post)]
        //public ActionResult Delete(int id, string confirmButton)
        //{

        //    Cliente cliente = _context.Clientes.SingleOrDefault(c => c.Id == id);

        //    if (cliente == null)
        //    {
        //        return HttpNotFound();
        //    }

        //    _context.Clientes.Remove(cliente);
        //    _context.SaveChanges();

        //    return View("Deleted");
        //}

    }
}

LojaDeGames/Controllers/GamesController.cs
using LojaDeGames.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LojaDeGames.Controllers
{
   
    public class GamesController : Controller
    {

        private ApplicationDbContext _context;

        public GamesController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

   //     static List<Jogo> listaJogos = new List<Jogo>()
     //   {
       //     new Jogo{Id = 1,Nome = "GTA V",Genero = "Ação",FaixaEtaria = "18+",Desenvolvedora =  "ROCKSTAR GAMES"},
        //    new Jogo{Id = 2,Nome = "Red Dead Redemption",Genero = "Aventura",FaixaEtaria = "18+",Desenvolvedora =  "ROCKSTAR GAMES"},
         //   new Jogo{Id = 3,Nome = "Monster Hunter",Genero = "Aventura",FaixaEtaria = "12+",Desenvolvedora =  "Capcom"},
           // new Jogo{Id = 4,Nome = "Street Fighter V",Genero = "Luta",FaixaEtaria = "12+",Desenvolvedora =  "Capcom"},
            //new Jogo{Id = 5,Nome = "Resident Evil VII",Genero = "Ação|Horror",FaixaEtaria = "16+",Desenvolvedora =  "Capcom"},
            //new Jogo{Id = 6,Nome = "Destiny 2",Genero = "Ação|Aventura",FaixaEtaria = "12+",Desenvolvedora =  "Bungie"}
        //};


        public ActionResult Index()
        {

            var gameIndexView = new JogoIndexViewModel()
            {
                Jogos = _context.Jogos.ToList()
            };

            return View(gameIndexView);

        }

        public ActionResult DetalhesJogos(int id)
        {
            if (id > _context.Jogos.Count()) return HttpNotFound();

            Jogo jogoDetalhe = _context.Jogos.Find(id);//(clientes => clientes.Id == id);

            return View(jogoDetalhe);

        }

        public ActionResult New()
        {
            var viewModel = new JogoIndexViewModel();

            return View("FormJogo", viewModel);
        }


        [HttpPost] // só será acessada com POST
        [ValidateAntiForgeryToken]
        public ActionResult Save(Jogo jogo)
        {
            ModelState.Remove("jogo.Id");

            if (!ModelState.IsValid)
            {
                var viewModel = new JogoIndexViewModel
                {
                     Jogo = jogo
                };

                return View("FormJogo", viewModel);
            }

            if (jogo.Id != 0)
            {
                _context.Entry(jogo).State = System.Data.Entity.EntityState.Modified;
            }
            else
            {
                _context.Jogos.Add(jogo);
            }
            // armazena o cliente em memória

            // faz a persistência
            _context.SaveChanges();
            // Voltamos para a lista de clientes
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var jogo = _context.Jogos.SingleOrDefault(c => c.Id == id);

            if (jogo == null)
                return HttpNotFound();

            var viewModel = new JogoIndexViewModel()
            {
                Jogo = jogo
            };

            return View("FormJogo", viewModel);
        }


        public ActionResult Delete(int id)
        {

            Jogo jogo = _context.Jogos.SingleOrDefault(c => c.Id == id);

            if (jogo == null)
            {
                return HttpNotFound();
            }
            else
            {
                _context.Jogos.Remove(jogo);
                _context.SaveChanges();
                return RedirectToAction("Index", jogo);
            }
        }
    }
}

LojaDeGames/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LojaDeGames.Controllers
{
    public class HomeController : Controller
    {
        
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

LojaDeGames/Controllers/VideoGController.cs
using LojaDeGames.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LojaDeGames.Controllers
{
    
    public class VideoGController : Controller
    {

        private ApplicationDbContext _context;

        public VideoGController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        public ActionResult IndexConsole()
        {
            var videoGameIndexview = new VideoGIndexViewModel()
            {
                VideoGs = _context.VideoGs.ToList()
            };

            return View(videoGameIndexview);
        }


        public ActionResult DetalhesVideoGame(int id)
        {
            if (id > _context.VideoGs.Count()) return HttpNotFound();

            VideoG videoDetalhe = _context.VideoGs.Find(id);//(clientes => clientes.Id == id);

            return View(videoDetalhe);

        }

        public ActionResult New()
        {
            var viewModel = new VideoGIndexViewModel();

            return View("FormVideoGame", viewModel);
        }


        [HttpPost] // só será acessada com POST
        [ValidateAntiForgeryToken]
        public ActionResult Save(VideoG videoG)
        {
            ModelState.Remove("videoG.Id");

            if (!ModelState.IsValid)
            {
                var viewModel = new VideoGIndexViewModel
                {
                    VideoG = videoG
                };

                return View("FormVideoGame", viewModel);
            }

            if (videoG.Id != 0)
            {
                _context.Entry(videoG).State = System.Data.Entity.EntityState.Modified;
            }
            else
            {
                _context.VideoGs.Add(videoG);
            }
            _context.SaveChanges();
            return RedirectToAction("IndexConsole");
        }

        public ActionResult Edit(int id)
        {
            var videoG = _context.VideoGs.SingleOrDefault(c => c.Id == id);

            if (videoG == null)
                return HttpNotFound();

            var viewModel = new VideoGIndexViewModel()
            {
                VideoG = videoG
            };

            return View("FormVideoGame", viewModel);
        }


        public ActionResult Delete(int id)
        {

            VideoG videoG = _context.VideoGs.SingleOrDefault(c => c.Id == id);

            if (videoG == null)
            {
                return HttpNotFound();
            }
            else
            {
                _context.VideoGs.Remove(videoG);
                _context.SaveChanges();
                return RedirectToAction("IndexConsole", videoG);
            }
        }
    }
}

LojaDeGames/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

LojaDeGames/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

LojaDeGames/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<style>


#jogo{
     margin:10px;
        width:200px;
        height:200px;
        background-image: url(../../Imagens/JogoIcone.png);
        background-size:100%;
    }

#cliente{
     margin:10px;
        width:200px;
        height:200px;
        background-image: url(../../Imagens/ClienteIcone.png);
        background-size:100%;
    }

#console{
     margin:10px;
        width:200px;
        height:200px;
        background-image: url(../../Imagens/ConsoleIcone.png);
        background-size:100%;
    }

#acessorio{
        margin:10px;
        width:200px;
        height:200px;
        background-image: url(../../Imagens/AcessorioIcone.png);
        background-size:100%;
}

    #box {

        margin: 0 auto;
        text-align:center;
        margin-top:15%;
        margin-bottom:15%;

    }


</style>



<div id="box">
   
        <button id="jogo" onclick="@("window.location.href='" + Url.Action("Index", "Games") + "'");"></button>
    
        <button id="cliente" onclick="@("window.location.href='" + Url.Action("IndexCliente", "Cliente") + "'");"></button>
    
        <button id="console" onclick="@("window.location.href='" + Url.Action("IndexConsole", "VideoG") + "'");"></button>
    
        <button id="acessorio"></button>


    
  
</div>























<!--<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div> -->